modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mcnoesisgui"
version = "${version}"
displayName = "MCNoesisGUI"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.mcnoesisgui]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcnoesisgui]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "mcnoesisgui.mixins.json"
